const state = { mode: 'text', previewId: null, pages: 0, imageId: null, previewTimer: null };
const $ = (selector) => document.querySelector(selector);
function notice(message, type = '') { const node = $('#notice'); node.textContent = message; node.className = `notice ${type}`; }
async function api(url, options = {}) { const response = await fetch(url, options); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Ocurrió un error inesperado.'); return data; }
function commonOptions() { return { width_mm: $('#width-mm').value, height_mm: $('#height-mm').value, media: $('#media').value }; }
function printOptions() { return { ...commonOptions(), preview_id: state.previewId, transport: $('#transport').value, copies: $('#copies').value, mac: $('#printer-mac').value }; }
function setMode(mode) { state.mode = mode; document.querySelectorAll('.mode').forEach((button) => button.classList.toggle('active', button.dataset.mode === mode)); document.querySelectorAll('.mode-panel').forEach((panel) => panel.classList.add('hidden')); $(`#${mode}-panel`).classList.remove('hidden'); $('#preview-title').textContent = mode === 'image' ? 'Tu imagen térmica' : mode === 'notion' ? 'Tu entrenamiento' : 'Tu etiqueta'; }
function textPayload() { return { ...commonOptions(), text: $('#text-content').value, header: $('#text-header').value, align: $('#text-align').value, font_size: $('#font-size').value, border: $('#text-border').checked }; }
function imagePayload() { return { ...commonOptions(), image_id: state.imageId, title: $('#image-title').value, fit: $('#image-fit').value, effect: $('#image-effect').value, contrast: $('#image-contrast').value }; }
function refreshImages() { if (!state.previewId) return; const timestamp = Date.now(); const labels = Array.from({length:state.pages}, (_, index) => `<div class="label-preview"><span>Etiqueta ${index + 1}</span><img alt="Vista previa de etiqueta ${index + 1}" src="/api/previews/${state.previewId}/${index + 1}?t=${timestamp}"></div>`).join(''); $('#preview-stage').innerHTML = `<div class="label-stack">${labels}</div>`; $('#page-count').textContent = `${state.pages} etiqueta${state.pages === 1 ? '' : 's'}`; $('#print-button').disabled = false; }
function clearPreview(message) { state.previewId = null; state.pages = 0; $('#preview-stage').innerHTML = '<div class="empty-preview"><span>✦</span><p>No hay contenido para previsualizar.</p></div>'; $('#page-count').textContent = 'Sin contenido'; $('#print-button').disabled = true; notice(message); }
async function preview() { try { if (state.mode === 'notion') { setMode('text'); notice('Pegá el entrenamiento por ahora; la conexión de Notion llegará en el próximo paso.'); return; } if (state.mode === 'text' && !$('#text-content').value.trim()) { clearPreview('Escribí el texto o pegá el entrenamiento que querés imprimir.'); return; } if (state.mode === 'image' && !state.imageId) { clearPreview('Elegí una imagen para crear su vista previa.'); return; } notice('Generando la vista previa…'); const endpoint = state.mode === 'image' ? '/api/preview/image' : '/api/preview/text'; const result = await api(endpoint, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(state.mode === 'image' ? imagePayload() : textPayload()) }); state.previewId = result.preview_id; state.pages = result.pages; refreshImages(); notice(`Vista previa lista: ${result.pages} etiqueta(s).`, 'success'); } catch (error) { notice(error.message, 'error'); } }
function schedulePreview() { clearTimeout(state.previewTimer); if (state.mode === 'notion') return; if (state.mode === 'text' && !$('#text-content').value.trim()) { clearPreview('Escribí el texto o pegá el entrenamiento que querés imprimir.'); return; } if (state.mode === 'image' && !state.imageId) return; notice('Actualizando vista previa…'); state.previewTimer = setTimeout(preview, 350); }
async function uploadImage(file) { const form = new FormData(); form.append('image', file); notice('Cargando imagen…'); const result = await api('/api/images/upload', {method:'POST', body:form}); $('#selected-image-name').textContent = result.name || 'Imagen seleccionada'; await selectImage(result); }
async function selectImage(result) { state.imageId = result.image_id; const box = $('#selected-image'); box.classList.remove('hidden'); box.querySelector('img').src = result.image_url; notice('Convirtiendo la imagen para papel térmico…'); await preview(); }
async function searchImages() { try { notice('Buscando imágenes…'); const data = await api('/api/images/search', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({query:$('#image-search').value.trim()})}); const results = $('#search-results'); results.innerHTML = ''; data.results.forEach((item) => { const button = document.createElement('button'); button.className = 'search-result'; button.title = item.title; button.innerHTML = `<img src="${item.thumbnail}" alt="${item.title}">`; button.addEventListener('click', async () => { try { notice('Importando imagen…'); await selectImage(await api('/api/images/import', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({source_url:item.source_url})})); } catch (error) { notice(error.message, 'error'); } }); results.appendChild(button); }); notice(data.results.length ? `${data.results.length} imágenes encontradas.` : 'No se encontraron imágenes.'); } catch (error) { notice(error.message, 'error'); } }
async function printLabels() { try { if (!state.previewId) throw new Error('Primero generá una vista previa.'); const { print_id } = await api('/api/print', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(printOptions())}); $('#print-button').disabled = true; const timer = setInterval(async () => { try { const status = await api(`/api/print/${print_id}`); notice(status.message); if (status.state !== 'running') { clearInterval(timer); $('#print-button').disabled = false; notice(status.message, status.state === 'done' ? 'success' : 'error'); } } catch (error) { clearInterval(timer); $('#print-button').disabled = false; notice(error.message, 'error'); } }, 700); } catch (error) { notice(error.message, 'error'); } }
async function printerStatus() { try { notice('Consultando la impresora…'); const data = await api('/api/printer/status', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({mac:$('#printer-mac').value})}); notice(data.message, 'success'); } catch (error) { notice(error.message, 'error'); } }
document.querySelectorAll('.mode').forEach((button) => button.addEventListener('click', () => setMode(button.dataset.mode)));
$('#print-button').addEventListener('click', printLabels); $('#status-button').addEventListener('click', printerStatus); $('#search-button').addEventListener('click', searchImages); $('#image-search').addEventListener('keydown', (event) => { if (event.key === 'Enter') searchImages(); }); $('#image-upload').addEventListener('change', (event) => { if (event.target.files[0]) uploadImage(event.target.files[0]).catch((error) => notice(error.message, 'error')); });
document.querySelectorAll('#text-panel input, #text-panel textarea, #text-panel select, #image-title, #image-fit, #image-effect, #image-contrast, #media, #width-mm, #height-mm').forEach((field) => { field.addEventListener('input', schedulePreview); field.addEventListener('change', schedulePreview); });
preview();
